### PR TITLE
Announce right addresses and CORS

### PR DESCRIPTION
**Pull request by simonovic86**
- announce reachable addresses (load balancer, etc)
- add CORS parameters to the IPFS HTTP API
- fix `tsconfig.json`
- rename `IPFS_API_ONLY` to `IPFS_ENABLE_API` (**default**=`true`)
- rename `IPFS_GATEWAY_ONLY` to `IPFS_ENABLE_GATEWAY` (**default**=`true`)
- fix IPFS dependency issue

### CODE REVIEW

**Review by oed — APPROVED** [review]
lgtm. This just enables the ipfs instance to announce the correct address right?

**Review by v-stickykeys — COMMENTED** [review]
LGTM :)

**Comment by simonovic86** [comment]
> lgtm. This just enables the ipfs instance to announce the correct address right?

It also adds CORS parameters to the IPFS HTTP API and renames flags.

**Review by v-stickykeys — APPROVED** [review]
Great!

**Pull request merged**
